-- HyperTracker Postgres/Supabase schema
-- Generated from the current SQLite production schema and query patterns.
-- Safe to apply to a fresh Supabase project.

create table if not exists public.users (
    telegram_id bigint primary key,
    username text,
    created_at timestamptz not null
);

create table if not exists public.wallets (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(telegram_id) on delete cascade,
    address text not null,
    alias text,
    filters_json jsonb not null,
    active boolean not null default true,
    created_at timestamptz not null,
    unique (user_id, address)
);

create index if not exists idx_wallets_user_id on public.wallets(user_id);
create index if not exists idx_wallets_address on public.wallets(address);
create index if not exists idx_wallets_active on public.wallets(active);

create table if not exists public.settings (
    user_id bigint primary key references public.users(telegram_id) on delete cascade,
    liq_monitor_enabled boolean not null default false,
    liq_filters_json jsonb not null,
    global_wallet_filters_json jsonb
);

create table if not exists public.wallet_fill_events (
    id bigint generated by default as identity primary key,
    wallet_id bigint not null references public.wallets(id) on delete cascade,
    user_id bigint not null references public.users(telegram_id) on delete cascade,
    wallet_address text not null,
    coin text not null,
    side text not null,
    price double precision not null,
    size double precision not null,
    notional_usd double precision not null,
    event_time_ms bigint not null,
    event_time_iso timestamptz not null,
    hash text,
    fee double precision,
    liquidation boolean not null default false,
    is_close boolean not null default false,
    dir text,
    event_id text not null unique,
    created_at timestamptz not null
);

create index if not exists idx_fill_events_wallet_time
    on public.wallet_fill_events(wallet_id, event_time_ms);
create index if not exists idx_fill_events_user_time
    on public.wallet_fill_events(user_id, event_time_ms);
create index if not exists idx_fill_events_wallet_coin_time
    on public.wallet_fill_events(wallet_id, coin, event_time_ms);

create table if not exists public.wallet_hourly_summary_state (
    wallet_id bigint primary key references public.wallets(id) on delete cascade,
    last_completed_hour_start_ms bigint,
    updated_at timestamptz not null
);

create table if not exists public.wallet_live_snapshots (
    wallet_id bigint primary key references public.wallets(id) on delete cascade,
    user_id bigint not null references public.users(telegram_id) on delete cascade,
    wallet_address text not null,
    account_value double precision not null default 0,
    total_notional_usd double precision not null default 0,
    total_margin_used double precision not null default 0,
    withdrawable double precision not null default 0,
    positions_count integer not null default 0,
    long_positions_count integer not null default 0,
    short_positions_count integer not null default 0,
    net_exposure_bias text not null default 'flat',
    positions_json jsonb not null,
    raw_snapshot_json jsonb not null,
    snapshot_time_ms bigint not null,
    snapshot_time_iso timestamptz not null,
    updated_at timestamptz not null
);

create index if not exists idx_wallet_live_snapshots_user_id
    on public.wallet_live_snapshots(user_id);
create index if not exists idx_wallet_live_snapshots_snapshot_time
    on public.wallet_live_snapshots(snapshot_time_ms desc);

create table if not exists public.evm_tracked_addresses (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(telegram_id) on delete cascade,
    address text not null,
    label text not null,
    address_type text not null,
    token_contract text,
    token_symbol text,
    min_value_usd double precision not null default 0.0,
    active boolean not null default true,
    created_at timestamptz not null,
    unique (user_id, address)
);

create index if not exists idx_evm_address on public.evm_tracked_addresses(address);
create index if not exists idx_evm_active on public.evm_tracked_addresses(active);
create index if not exists idx_evm_user_id on public.evm_tracked_addresses(user_id);

comment on table public.wallet_fill_events is
    'High-volume historical fill stream used for notifications, hourly summaries, and dashboard analytics.';

comment on table public.wallet_live_snapshots is
    'Latest merged live account state per tracked wallet, including HIP-3 dex positions.';
